apiVersion: apps/v1
kind: Deployment
metadata:
  name: tallermgf-api
  namespace: tallermgf
  labels:
    app: tallermgf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tallermgf-api
  template:
    metadata:
      labels:
        app: tallermgf-api
    spec:
      imagePullSecrets:
        - name: ghcr-creds # creado más abajo si el repo es privado
      containers:
        - name: api
          image: ghcr.io/OWNER/TallerMGF:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # Ejemplo de variables si usas properties.py/envs
            - name: FLASK_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
