apiVersion: apps/v1
kind: Deployment
metadata:
  name: tallermgf
  namespace: tallermgf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tallermgf
  template:
    metadata:
      labels:
        app: tallermgf
    spec:
      containers:
      - name: tallermgf
        image: okteto/sample-app:latest   # 👈 imagen pública en Docker Hub
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 5
          periodSeconds: 5
