apiVersion: apps/v1
kind: Deployment
metadata:
  name: tallermgf
  namespace: tallermgf
  labels: { app: tallermgf }
spec:
  replicas: 1
  selector:
    matchLabels: { app: tallermgf }
  template:
    metadata:
      labels: { app: tallermgf }
    spec:
      containers:
      - name: tallermgf
        image: lgeronimom/tallermgf:latest   # ← se actualiza por CI, pero deja "latest" aquí
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080               # ← tu app escucha en 8080
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests: { memory: "64Mi", cpu: "50m" }
          limits:   { memory: "128Mi", cpu: "100m" }
        livenessProbe:
          httpGet: { path: /health, port: 8080 }  # ← /health en 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet: { path: /health, port: 8080 }  # ← /health en 8080
          initialDelaySeconds: 3
          periodSeconds: 5
