name: restart-on-push
on:
  push:
    branches: ["master"]   # o "main" si cambiaste de rama
  workflow_dispatch: {}

jobs:
  restart:
    runs-on: self-hosted
    env:
      KUBECONFIG: /home/github/.kube/config
    steps:
      - uses: actions/checkout@v4

      - name: Rollout restart
        run: |
          kubectl -n tallermgf rollout restart deployment/tallermgf-api
          kubectl -n tallermgf rollout status deployment/tallermgf-api --timeout=180s

      - name: Show service/ingress
        run: kubectl -n tallermgf get deploy,po,svc,ing -o wide
